/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

allprojects { repositories { mavenCentral() } }

tasks.withType<Test>().configureEach { useJUnitPlatform() }

kotlin {
  sourceSets.main { kotlin.srcDir("build/generated/ksp/main/kotlin") }
  sourceSets.test { kotlin.srcDir("build/generated/ksp/test/kotlin") }
}

plugins {
  // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
  id("org.jetbrains.kotlin.jvm") version "1.8.10"

  id("com.google.devtools.ksp") version "1.8.10-1.0.9"
}

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

dependencies {
  implementation(platform("io.arrow-kt:arrow-stack:1.0.1"))

  implementation("io.arrow-kt:arrow-core")
  implementation("io.arrow-kt:arrow-fx-coroutines")
  implementation("io.arrow-kt:arrow-optics")
  ksp("io.arrow-kt:arrow-optics-ksp-plugin:1.1.5")

  val kotestVersion = "5.5.5"
  testImplementation("io.kotest:kotest-runner-junit5:$kotestVersion")
  testImplementation("io.kotest:kotest-assertions-core:$kotestVersion")
}

tasks.named<Test>("test") {
  // Use JUnit Platform for unit tests.
  useJUnitPlatform()
}
