/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package arrow.crash.course

import io.kotest.assertions.fail
import io.kotest.core.spec.style.StringSpec

class AppTest: StringSpec({
    "foo" {
        fail("oop")
    }
})
